### ISSUE TITLE
`expect-expect` doesn't accept `assert`

### ISSUE THREAD

**Issue by fregante** [vitest-dev/eslint-plugin-vitest#502]
`assert` is a first-class tester in Vitest: https://vitest.dev/api/assert

The rule seems to only focus on `expect` but it doesn't need to be. Tests are valid as long as they _test_ something, regardless of how they do that.

**Comment by veritem** [comment]
fixed in #504

**Comment by fregante** [comment]
I'm still seeing the issue in v1.0.2

```js
test('cleanPrCommitTitle', () => {
	const clean = 'Something done';
	assert.equal(cleanPrCommitTitle('Something done (#123)', 123), clean);
	assert.equal(cleanPrCommitTitle('  Something done  (#123)  ', 123), clean);
	assert.equal(cleanPrCommitTitle(' Something done ', 123), clean);

	assert.notEqual(cleanPrCommitTitle('Something done (fixes #123)', 123), clean);
	assert.notEqual(cleanPrCommitTitle('Something done (#23454)', 123), clean);
});
```
<img width="694" alt="Screenshot 1" src="https://github.com/user-attachments/assets/56ec184e-e7cc-45d5-8083-13007608332e">

**Comment by veritem** [comment]
i'll investigate
